name: toon_photo_editor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  connectivity_plus:
  cached_network_image:
  get_it:
  carousel_slider: ^4.2.1
  pinch_zoom: ^1.0.0
  smooth_page_indicator: ^1.0.0+2
  get_storage:
  dio:
  http:
  rate_my_app:
  image_picker: ^0.8.0+4
  gallery_saver: ^2.3.2
  url_launcher: ^6.1.7
  fluttertoast:
  image_cropper: ^3.0.1
  screenshot:
  image_gallery_saver:
  permission_handler:
  flutter_svg:
  flutter_share_me: ^1.4.0
  google_fonts:
  vector_math:
  share_plus:
  path_provider:
  get: 4.6.5
  google_mobile_ads: ^3.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/